SELECT * FROM PAYMENT WHERE amount >= 500;
SELECT * FROM STUDENT WHERE birthday < DATEADD('YEAR', -20, CURRENT_DATE);
SELECT * FROM STUDENT WHERE GROUPNUMBER = 10 and BIRTHDAY >= DATEADD('YEAR', -20, CURRENT_DATE);
SELECT * FROM STUDENT WHERE NAME like '%Mike%' or GROUPNUMBER between 4 and 6;
SELECT * FROM PAYMENT WHERE payment_date >= DATEADD('MONTH', -8, CURRENT_TIMESTAMP);
SELECT * FROM STUDENT where NAME like 'A%';
SELECT * FROM STUDENT where NAME like 'Roxi%' and GROUPNUMBER = 4 or NAME like 'Tallie%' and GROUPNUMBER = 9;